apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
type: Opaque
data:
  credentials: W2RlZmF1bHRdCmF3c19hY2Nlc3Nfa2V5X2lkPUFLSUE2UkVDU0RLNUxCN0tKUlBSCmF3c19zZWNyZXRfYWNjZXNzX2tleT1mTEpHcGtaSW1wbk1BZThDTFdBMElaQU1XNXBWTnRYOEs3Z09FK1R0